use_frameworks!

platform :ios, '8.0'

target 'JKUIEventHandler_Example' do
  pod 'JKUIEventHandler', :path => '../'

  target 'JKUIEventHandler_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
